### ISSUE TITLE
Contact entry not recognised if @ is in the telegram field

### ISSUE THREAD

**Issue by mofosyne** [vbeskrovnov/obsidian-contacts#6]
Just discovered that if I added `@` to `telegram: thinkerer` like `telegram: @thinkerer` the contact plugin will not add the contact in... looks like a bug

Below is the minimum test file I used to replicate the issue

```
---
name:
  first: Test
  last: Tester
phone:
telegram: @Test
linkedin:
birthday:
last_chat:
friends:
type: contact
---
```

**Comment by vbeskrovnov** [comment]
Unfortunately, this is Obsidian API limitation, as a workaround you can use quotes:
```
---
name:
  first: Test
  last: Tester
phone:
telegram: "@Test"
linkedin:
birthday:
last_chat:
friends:
type: contact
---
```

But I will see if it makes sense to use custom yaml parser instead of Obsidian API.
